### ISSUE TITLE
Multipart uploading will not stop, when a part fails uploading

### ISSUE THREAD

**Issue by LordMike** [Genbox/SimpleS3#13]
If you upload a stream as multiple parts, and then abort / cancel one of the uploads using a network tool (e.g. Fiddler), you'll notice that the following parts are still uploaded. I assume the multipart will fail in the end, when S3 replies back that not all parts are present.

**Comment by Genbox** [comment]
I can't determine if it is better to abort the upload if a part fails or upload as much as possible.

The second method only works if the consumer is made aware of which parts failed, which is what happens in the current version of the API. I'm closing this for now - reopen if you want to discuss alternate approaches.
