### ISSUE TITLE
Document how to configure HttpClient options

### ISSUE THREAD

**Issue by LordMike** [Genbox/SimpleS3#22]
Such as timeout.

For reference, SimpleS3 (when using `HttpClientFactory`) uses a client named `SimpleS3`. It can be configured like such (I need infinite timeouts):

```csharp
var builder = services.AddSimpleS3Core();
builder.UseHttpClientFactory();

services.AddHttpClient("SimpleS3", client => client.Timeout = Timeout.InfiniteTimeSpan);
```

... buuut.. there's a simpler way, apparently. The `IHttpClientBuilder` from `UseHttpClientFactory()` allows one to configure the client:

```csharp
IHttpClientBuilder httpClientBuilder = builder
    .UseHttpClientFactory();

httpClientBuilder
    .ConfigureHttpClient(client => client.Timeout = Timeout.InfiniteTimeSpan);
```

**Comment by Genbox** [comment]
That's honestly the fault of Microsoft. They attach a lot of extensions to the service collection once you add their dependency. They make it convenient to use their libraries, but it is not a good design and adds confusion.

I'm working on streamlining how you can configure proxy, timeout etc. Documentation comes after.

**Comment by Genbox** [comment]
The streamlining is finished. Documentation can be found in the [SimpleS3.ExamplesAdvanced project.](https://github.com/Genbox/SimpleS3/blob/master/src/SimpleS3.ExamplesAdvanced/Program.cs#L110)
