### ISSUE TITLE
[feature] Implement GetBucketLifecycleConfiguration

### ISSUE THREAD

**Issue by LordMike** [Genbox/SimpleS3#37]
* [x] I hereby verify that I am a sponsor.
Sponsorship is required before you can submit feature requests. See https://github.com/sponsors/Genbox

**Describe the feature**
Please implement the `GetBucketLifecycleConfiguration` - the idea is to be able to sync a Lifecycle configuration with some desired set. In my use case, my application does not know what other rules there are on the given bucket - so in order to add my own, I need to fetch the existing configuration and send them back to S3 w/ `PutBucketLifecycleConfiguration`.

**Comment by Genbox** [comment]
Implemented in version 1.1.0
