### ISSUE TITLE
How does one list buckets?

### ISSUE THREAD

**Issue by LordMike** [Genbox/SimpleS3#4]
I can find create/delete/empty/list objects; but not List Buckets.

![image](https://user-images.githubusercontent.com/1027111/66396342-dc04fc00-e9d9-11e9-9d48-5f02de49acdf.png)

**Comment by Genbox** [comment]
The documentation had a section called "Service" with a "GetService" method underneath it - so I called it the same. However, Amazon JUST updated their documentation this weekend and now calls it "ListBuckets", which I think is a lot more fitting, so I will be updating the API to reflect this.

**Comment by Genbox** [comment]
The old docs are here: https://docs.aws.amazon.com/en_pv/AmazonS3/latest/API/archive-RESTServiceGET.html

New docs are here: https://docs.aws.amazon.com/en_pv/AmazonS3/latest/API/API_ListBuckets.html

I will be updating the rest of the API soon.
