### ISSUE TITLE
Bug: Adding SimpleS3 core to a DI container w/o Logging added, throws

### ISSUE THREAD

**Issue by LordMike** [Genbox/SimpleS3#43]
* [x] I hereby verify that I am a sponsor.
Sponsorship is required before you can submit bug reports. See https://github.com/sponsors/Genbox

**Describe the bug**
Using the library in its simplest form (empty DI container) throws on some instantiations, as it cannot resolve any `ILogger`'s. 

**How to reproduce?**
```csharp
var sc = new ServiceCollection();

var s3Core = SimpleS3CoreServices.AddSimpleS3Core(sc);
s3Core.UseAmazonS3();
s3Core.UseHttpClient();
sc.Configure<AmazonS3Config>(config =>
{
    config.Credentials = new StringAccessKey("MyKeyId", "MyAccessKey");
    config.Region = AmazonS3Region.EuWest1;
});

var provider = sc.BuildServiceProvider();
var myClient =  provider.GetRequiredService<IObjectClient>();
```

The above throws while creating `IObjectClient`, with:

```
System.InvalidOperationException: 'Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger`1[Genbox.SimpleS3.Core.Internals.Authentication.SigningKeyBuilder]' 
while attempting to activate 'Genbox.SimpleS3.Core.Internals.Authentication.SigningKeyBuilder'.'
```

**Expected behavior**
Theoretically, it should be possible to run with no logging available. Logging could be encapsulated in a new custom `MyLogger` which attempts to find the correct logger when instantiated. If no logger is available, `NullLogger` can be used.

**Comment by Genbox** [comment]
I have TODO proposed solutions:

#### Create a NullLogFactory
NullLogFactory inherits from ILoggerFactory. Ctor takes in a nullable ILoggerFactory and saves the reference in a field.
In the CreateLogger(string categoryName) method from the interface, I redirect the call to the field if it is not null. If it is, I simply return a NullLogger.Instance.

```csharp
public class NullLogFactory : ILoggerFactory
{
    private readonly ILoggerFactory? _factory;

    private NullLogFactory(ILoggerFactory? factory = null)
    {
        _factory = factory;
    }

    public void Dispose()
    {
        _factory?.Dispose();
        GC.SuppressFinalize(this);
    }

    public ILogger CreateLogger(string categoryName)
    {
        return _factory == null ? NullLogger.Instance : _factory.CreateLogger(categoryName);
    }

    public void AddProvider(ILoggerProvider provider)
    {
        _factory?.AddProvider(provider);
    }
}
```

The factory is registered with TryAddSingleton(), so in the case user has called AddLogging() before SimpleS3, the null logger won't be added to the service collection.

In the case the user calls AddLogging after SimpleS3, then logging won't be activated as AddLogging() from Microsoft.Extensions.Logging also calls TryAddSingleton on their ILoggerFactory service.

#### Change APIs to receive a ProxyLogger that inherits from ILogger
This requires a change to all APIs and would break backward compatibility. This is pretty much the same as changing all ILogger services to be optional around the code. It would make code readability worse.

**Comment by LordMike** [comment]
Note: Your `NullLogFactory` doesn't need to take a `ILoggerFactory` - in case it exists already, you don't add the factory and hence you don't receive it.. If you add it before, you still don't need it, as there is nothing to receive.

Best option is probably to require the user to add `ILogging` features.

**Comment by Genbox** [comment]
Yeah, it probably is. For the common usecase I'm going to call AddLogging() on the users behalf. In the advanced scenario like the code you have, I'm going to require that logging is already added. Otherwise, I have to depend on the concrete logging from Microsoft directly and I'd like to avoid that when possible.
