### ISSUE TITLE
Configuring HttpClient outside SimpleS3

### ISSUE THREAD

**Issue by LordMike** [Genbox/SimpleS3#44]
* [x] I hereby verify that I am a sponsor.
Sponsorship is required before you can submit feature requests. See https://github.com/sponsors/Genbox

**Describe the feature**
One of the benefits of IHttpClientFactory is that the user (me) can configure a HttpClient that some library can use, through DI, without that library having to accept a HttpClient from myself. It seems that SimpleS3 does not use a named client, meaning the user can only configure the HttpClients used, by configuring the default HttpClient provided by the factory.

If two libraries were to do this, it wouldn't be possible to customize the options for just one of them.

Allow an optional name to be provided when using the `UseHttpClientFactory()` extensions to let the user control this.

[Code that creates the default client](https://github.com/Genbox/SimpleS3/blob/0adbe0ee7fc6d2850ee46195012d86e2a746a067/src/SimpleS3.Extensions.HttpClientFactory/HttpClientFactoryNetworkDriver.cs#L45).

**Comment by Genbox** [comment]
Here is my proposal:

1. Create a configuration class for HttpClientFactoryNetworkDriver.
2. Have a HttpClientName property in the config
3. Call _clientFactory.CreateClient(config.HttpClientName)

Would that support the use case?

**Comment by LordMike** [comment]
It will.

As a convenience, you can add the following overloads:

* `UseHttpClientFactory(string clientName)` (calls the below, and sets the name)
* `UseHttpClientFactory(Action<Config> configure)`

**Comment by Genbox** [comment]
The second overload is already present. I'll keep that as the only one to avoid polluting the API with lots of different overloads.

**Comment by Genbox** [comment]
This was added in 41da3457cf883eaa7a900cf404a8c2221f4d8a0e
