### ISSUE TITLE
Add an DeleteAllObjectsAsync() overload accepting an optional prefix

### ISSUE THREAD

**Issue by LordMike** [Genbox/SimpleS3#45]
* [x] I hereby verify that I am a sponsor.
Sponsorship is required before you can submit feature requests. See https://github.com/sponsors/Genbox

**Describe the feature**
Add an overload to `DeleteAllObjectsAsync` that accepts a prefix (or add an optional parameter to the original one) such that the `DeleteAllObjectsAsync` call only deletes for a given prefix. Currently, `DeleteAllObjectsAsync` will empty a bucket.

**Comment by Genbox** [comment]
This has been implemented in an earlier commit
