### ISSUE TITLE
Expand header builders to support more of cache control

### ISSUE THREAD

**Issue by LordMike** [Genbox/SimpleS3#54]
* [x] I hereby verify that I am a sponsor.

**Description of the feature**
I'm setting up Cache-Control to control the caching of objects in GCP/GCS, but I'm unable to set the values as I intend.

As an example, on a PutRequest, I can use the `CacheControlBuilder` to do the following:

```csharp
request.CacheControl.Set(CacheControlType.MaxAge, 3600);
```

But from reading the code behind, I can't set multiple properties, like `public,max-age=3600` or `must-understand,no-store`. Additionally, I cannot set values that aren't defined in the `CacheControlType` enum - an example would be for caching proxies like Cloudflare that support `s-max-age` as a signal on how long CF should cache content, versus the end users. MDN has multiple other examples: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

Furthermore, I'm trying to abstract away SimpleS3 in my system, so I'm actually passing around headers like Cache-Control, as strings. This also makes it tricky to set it on the request, as I can't immediately find a ".Parse(string)" or ".Set(string)" method.

**Comment by Genbox** [comment]
For support of other cache headers, as well as multi-argument cache controls, I've extended HttpBuilders with a fix here: https://github.com/Genbox/HttpBuilders/commit/006fe1f187528361d8d26e4e352b08d50b213056

**Comment by Genbox** [comment]
This code shows how you can use multiple arguments: https://github.com/Genbox/HttpBuilders/blob/master/src/HttpBuilders.Tests/Builders/CacheControlBuilderTests.cs#L30

**Comment by Genbox** [comment]
Updated SimpleS3 to use the new HttpHeaders release. You can now use "Add()" on CacheControlBuilder to give it more complex cache logic. feature is available in 2.1.1
