### ISSUE TITLE
Backblaze upload failure with files exceeding a trivial size.

### ISSUE THREAD

**Issue by Ephron-WL** [Genbox/SimpleS3#55]
* [X] **I hereby verify that if I can get this project to work as expected for my use case that I will become a sponsor ;-)**

**Description of the bug**
Backblaze upload HTTP client issues when file is larger than a 26KB.  I was able to test this successfully with a 26KB file, but when I tested 460KB or larger I obtain this error after a few seconds.  I've attempted to debug the issue, but the call stack is a bit complex and maybe the author will have an easier time.

See exception:

![image](https://user-images.githubusercontent.com/43553209/228657220-8f66a6ee-2673-4bd8-9c2c-aaf273818c85.png)

![image](https://user-images.githubusercontent.com/43553209/228657307-2beff47e-9173-424d-a0aa-5fbcab2e9a2b.png)

**How to reproduce?**
```
			ServiceCollection services = new ServiceCollection();
			services.AddBackBlazeB2(config => {
				config.Credentials = new StringAccessKey("...", "...");
				config.Region = BackBlazeB2Region.UsWest002;
			});

			ServiceProvider provider = services.BuildServiceProvider();
			var client = provider.GetRequiredService<BackBlazeB2Client>();

                        // File size: 460KB+
			var upload = client.CreateUpload("BucketName", "Technical Details.pdf");
			var bytes = File.ReadAllBytes(@"c:\temp\Technical Details.pdf");
			await upload.UploadDataAsync(bytes);
```

**Expected behavior**
To upload the file without an exception.

**Comment by Genbox** [comment]
The exception leads me to believe it is a networking issue, but in that case, steams should not be read again. I'll try to replicate the issue.

**Comment by Genbox** [comment]
I can't replicate the issue with a 500 KB file, but there are issues with Backblaze when trying to upload a 5 MB file. I have tests that previously worked, and they no longer do, so I assume it is an issue with Backblaze.

I'll investigate some more.

**Comment by Genbox** [comment]
I found the issue. Every provider allows 2MB chunks when uploading using chunked streaming, except for Backblaze.
The standard chunk size in SimpleS3 is 2MB, but Amazon recommends 80KB, so I've changed the default to 80KB for compatibility.

I'll release a new version momentarily. It would be great if you could test if your issue is fixed.

**Comment by Genbox** [comment]
Version 2.2.0 has been released.

**Comment by Ephron-WL** [comment]
I tested this release.  It worked for the file in question.  However, as I scaled up the file size I encountered Task timeout exceptions.  There seems to be a 100 second   Maybe there is a config setting I'm missing? 
```
	var upload = client.CreateUpload("...", "FTOS-SI-ON-9.14.2.8.bin");
	var bytes = File.ReadAllBytes(@"c:\temp\FTOS-SI-ON-9.14.2.8.bin");
	await upload.UploadDataAsync(bytes);
```

![image](https://user-images.githubusercontent.com/43553209/229944453-4ea7c5dd-7cea-48d8-ba92-8ef45e62cf8a.png)

**Comment by Genbox** [comment]
It is not an issue with SimpleS3. I've copied your question to a discussion for you here: https://github.com/Genbox/SimpleS3/discussions/56
